version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_URL: postgresql://postgres:Statsspeak%40123@db.ounttrkvhnvhzfgtyklo.supabase.co:5432/postgres
    volumes:
      - .:/app
